# Generated by Django 6.0.2 on 2026-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '9998_seed_leave_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid by Company'), ('GOVERNMENT', 'Paid via Government (SSS/Employer)'), ('UNPAID', 'Unpaid')], default='UNPAID', help_text='Whether this leave is paid (company or government) or unpaid.', max_length=20),
        ),
    ]
