# Generated by Django 6.0.2 on 2026-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_approve_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_approve_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_records',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_lock_payroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('HRADMIN', 'HR Admin'), ('HRASSISTANT', 'HR Assistant')], default='HRASSISTANT', max_length=20),
        ),
    ]
