# Generated by Django 6.0.2 on 2026-08-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_can_approve_leave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_approve_overtime',
            new_name='can_manage_overtime',
        ),
    ]
