# Generated by Django 6.0.2 on 2026-08-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_can_approve_overtime_profile_can_manage_overtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_approve_leave',
            new_name='can_manage_leave',
        ),
    ]
