# Generated by Django 6.0.2 on 2026-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_can_approve_leave_profile_can_manage_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_manage_leave_adjustments',
            field=models.BooleanField(default=False),
        ),
    ]
