# Generated by Django 6.0.2 on 2026-09-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_can_manage_leave_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_import_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
