# Generated by Django 6.0.2 on 2026-02-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_titles', to='employees.department')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('employment_status', models.CharField(choices=[('REGULAR', 'Regular'), ('PROBATIONARY', 'Probationary'), ('CONTRACTUAL', 'Contractual'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='PROBATIONARY', max_length=20)),
                ('date_hired', models.DateField()),
                ('date_of_resignation', models.DateField(blank=True, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('mothers_maiden_name', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced')], max_length=1)),
                ('permanent_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('sss_gsis_no', models.CharField(blank=True, max_length=20)),
                ('hdmf', models.CharField(blank=True, max_length=20)),
                ('philhealth', models.CharField(blank=True, max_length=20)),
                ('drivers_license', models.CharField(blank=True, max_length=20)),
                ('passport', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobtitle')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
