# Generated by Django 6.0.2 on 2026-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tax_status',
            field=models.CharField(choices=[('S/0', 'Single, 0 dependents'), ('S/1', 'Single, 1 dependent'), ('S/2', 'Single, 2 dependents'), ('S/3', 'Single, 3 dependents'), ('S/4', 'Single, 4 dependents'), ('ME/0', 'Married, 0 dependents'), ('ME/1', 'Married, 1 dependent'), ('ME/2', 'Married, 2 dependents'), ('ME/3', 'Married, 3 dependents'), ('ME/4', 'Married, 4 dependents')], default='S/0', help_text='BIR tax status for withholding tax computation.', max_length=10),
        ),
    ]
