# Generated by Django 6.0.2 on 2026-02-24 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
        ("employees", "0002_attendance"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="Attendance"),
            ],
        )
    ]
