# Generated by Django 6.0.2 on 2026-10-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_tax_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_id', models.PositiveIntegerField(help_text='Device-local finger ID used in ZK9500 SDK')),
                ('template', models.BinaryField(help_text='Raw fingerprint template from ZK9500')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='employees.employee')),
            ],
            options={
                'ordering': ['employee', 'finger_id'],
                'unique_together': {('employee', 'finger_id')},
            },
        ),
    ]
