# Generated by Django 6.0.2 on 2026-03-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_move_attendance_to_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_monday', models.BooleanField(default=False)),
                ('is_tuesday', models.BooleanField(default=False)),
                ('is_wednesday', models.BooleanField(default=False)),
                ('is_thursday', models.BooleanField(default=False)),
                ('is_friday', models.BooleanField(default=False)),
                ('is_saturday', models.BooleanField(default=False)),
                ('is_sunday', models.BooleanField(default=False)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.workschedule'),
        ),
    ]
