# Generated by Django 6.0.2 on 2026-08-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-llm_score']},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='matching_keywords',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='similarity_score',
        ),
        migrations.AddField(
            model_name='candidate',
            name='anonymized_text',
            field=models.TextField(blank=True, help_text='Resume text after anonymisation'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='llm_justification',
            field=models.TextField(blank=True, help_text='Two‑sentence explanation from the AI'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='llm_score',
            field=models.FloatField(blank=True, help_text='Score 0–100 from DeepSeek', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
