# Generated by Django 6.0.2 on 2026-05-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('holiday_type', models.CharField(choices=[('REGULAR', 'Regular Holiday'), ('SPECIAL_NON_WORKING', 'Special Non-Working Day')], default='REGULAR', max_length=30)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage rate e.g. 200 for 200%', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
