# Generated by Django 6.0.2 on 2026-08-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_day_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=5)),
                ('rest_day_multiplier', models.DecimalField(decimal_places=2, default=1.69, max_digits=5)),
                ('special_non_working_holiday_multiplier', models.DecimalField(decimal_places=2, default=1.69, max_digits=5)),
                ('special_day_on_rest_day_multiplier', models.DecimalField(decimal_places=2, default=1.95, max_digits=5)),
                ('regular_holiday_multiplier', models.DecimalField(decimal_places=2, default=2.6, max_digits=5)),
                ('regular_holiday_on_rest_day_multiplier', models.DecimalField(decimal_places=2, default=3.38, max_digits=5)),
                ('rest_day_first8_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=5)),
                ('special_non_working_first8_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=5)),
                ('special_on_rest_day_first8_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('regular_holiday_first8_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('regular_on_rest_day_first8_multiplier', models.DecimalField(decimal_places=2, default=2.6, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
