# Generated by Django 6.0.2 on 2026-03-02 09:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(unique=True)),
                ('holiday_type', models.CharField(choices=[('REGULAR', 'Regular Holiday'), ('SPECIAL_NON_WORKING', 'Special Non-Working Holiday'), ('SPECIAL_WORKING', 'Special Working Holiday')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage rate e.g. 200 for 200%', max_digits=5)),
                ('is_no_work_no_pay', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHoliday',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('holiday_type', models.CharField(choices=[('REGULAR', 'Regular Holiday'), ('SPECIAL_NON_WORKING', 'Special Non-Working Holiday'), ('SPECIAL_WORKING', 'Special Working Holiday')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage rate e.g. 200 for 200%', max_digits=5)),
                ('is_no_work_no_pay', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical holiday',
                'verbose_name_plural': 'historical holidays',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
