# Generated by Django 6.0.2 on 2026-08-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='PHILIPPINE HOME PHARMACEUTICAL', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
        ),
        migrations.CreateModel(
            name='PagIBIGContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_share', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['salary_from'],
            },
        ),
        migrations.CreateModel(
            name='PhilHealthContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('employee_share_rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'ordering': ['salary_from'],
            },
        ),
        migrations.CreateModel(
            name='SSSContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_salary_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_share', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['salary_from'],
            },
        ),
        migrations.CreateModel(
            name='WithholdingTaxTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensation_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compensation_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_above', models.DecimalField(decimal_places=4, max_digits=5)),
                ('exemption_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['compensation_from'],
            },
        ),
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('period_type', models.CharField(choices=[('REGULAR', 'Regular'), ('THIRTEENTH_MONTH', '13th Month Pay')], default='REGULAR', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('late_deduction_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total late deduction for the period', max_digits=12)),
                ('absent_deduction_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total absence deduction for the period', max_digits=12)),
                ('holiday_pay_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total additional holiday pay for the period', max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=10)),
                ('undertime_deduction_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total undertime deduction for the period', max_digits=12)),
                ('sss_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('philhealth_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pagibig_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_regular_pay', models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime pay for ordinary working days', max_digits=12)),
                ('overtime_special_pay', models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime pay for rest days, special non‑working holidays, regular holidays, etc.', max_digits=12)),
                ('absence_count', models.PositiveIntegerField(default=0)),
                ('absence_dates', models.JSONField(blank=True, help_text='List of absence dates', null=True)),
                ('leave_count', models.PositiveIntegerField(default=0)),
                ('leave_dates', models.JSONField(blank=True, help_text='List of leave dates', null=True)),
                ('nsd_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Night Shift Differential for the period', max_digits=12)),
                ('remaining_leave_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rest_day_premium_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total rest day premium for the period', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payperiod')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name'],
                'unique_together': {('employee', 'pay_period')},
            },
        ),
        migrations.CreateModel(
            name='PayslipAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative = deduction (e.g., loan), positive = addition (e.g., bonus)', max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipDailyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('working_day', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('HOLIDAY', 'Holiday'), ('REST_DAY', 'Rest Day')], default='PRESENT', max_length=15)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('absent_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('undertime_minutes', models.PositiveIntegerField(default=0)),
                ('undertime_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('holiday', models.CharField(blank=True, help_text="Holiday name if applicable, e.g., 'Independence Day'", max_length=100, null=True)),
                ('holiday_type', models.CharField(blank=True, help_text='e.g., REGULAR, SPECIAL_NON_WORKING', max_length=30, null=True)),
                ('holiday_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('leave_type_name', models.CharField(blank=True, help_text='e.g., Vacation Leave, Sick Leave, if the day was an approved leave', max_length=100, null=True)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime_type', models.CharField(blank=True, help_text='e.g., ORDINARY, REST_DAY, REGULAR_HOLIDAY', max_length=30, null=True)),
                ('rest_day_premium', models.DecimalField(decimal_places=2, default=0.0, help_text='Rest day premium for this day', max_digits=10)),
                ('night_shift_diff', models.DecimalField(decimal_places=2, default=0.0, help_text='NSD pay for this day', max_digits=10)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_details', to='payroll.payslip')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('payslip', 'date')},
            },
        ),
    ]
