# Generated by Django 6.0.2 on 2026-09-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipdailydetail',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('HOLIDAY', 'Holiday'), ('REST_DAY', 'Rest Day'), ('PAID_LEAVE', 'Paid Leave')], default='PRESENT', max_length=15),
        ),
    ]
