# Generated by Django 6.0.2 on 2026-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payslipdailydetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withholdingtaxtable',
            name='tax_status',
            field=models.CharField(default='S/0', max_length=10),
        ),
    ]
