# Generated by Django 6.0.2 on 2026-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_withholdingtaxtable_tax_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
