# Generated by Django 6.0.2 on 2026-02-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0002_attendance"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Attendance",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("date", models.DateField()),
                        ("time_in", models.TimeField(blank=True, null=True)),
                        ("time_out", models.TimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "employee",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="attendances",
                                to="employees.employee",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["-date"],
                        "unique_together": {("employee", "date")},
                        "db_table": "employees_attendance",
                    },
                )
            ],
        )
    ]
