# Generated by Django 6.0.2 on 2026-02-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table=None,
        ),
    ]
