# Generated by Django 6.0.2 on 2026-02-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_table'),
        ('employees', '0003_move_attendance_to_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BiometricMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_number', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_mapping', to='employees.employee')),
            ],
            options={
                'ordering': ['biometric_number'],
            },
        ),
    ]
