# Generated by Django 6.0.2 on 2026-02-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_is_manual_entry_attendance_remarks_and_more'),
        ('employees', '0003_move_attendance_to_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('overtime_type', models.CharField(choices=[('REGULAR', 'Regular Overtime'), ('REST_DAY', 'Rest Day'), ('SPECIAL_HOLIDAY', 'Special Holiday'), ('REGULAR_HOLIDAY', 'Regular Holiday'), ('SPECIAL', 'Special')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_start_time', models.TimeField()),
                ('requested_end_time', models.TimeField()),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_approvals', to='employees.employee')),
                ('colleague_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_references', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to='employees.employee')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_filed', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
