# Generated by Django 6.0.2 on 2026-02-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_overtimerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='overtime_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Overtime'), ('REST_DAY', 'Rest Day'), ('SPECIAL_HOLIDAY', 'Special Holiday'), ('REGULAR_HOLIDAY', 'Regular Holiday')], default='REGULAR', max_length=20),
        ),
    ]
