# Generated by Django 6.0.2 on 2026-02-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_overtimerequest_overtime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
